apps/travelplan_app/urls.py
from django.conf.urls import url,include
from . import views
urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^register$',views.register,name='register'),
    url(r'^login$',views.login,name='login'),
    url(r'^logout$',views.logout,name='logout'),
    url(r'^add$',views.add,name='add'),
    url(r'^travels$',views.travels,name='travels'),
    url(r'^showadd$',views.showadd,name='showadd'),
    url(r'^joinTrip/(?P<id>\d+)$',views.joinTrip,name='joinTrip'),
    url(r'^destination/(?P<id>\d+)$',views.destination,name='destination'),
    url(r'^delete$',views.delete,name='delete')

]

travelplan/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('apps.travelplan_app.urls',namespace="travelplan"))
]

apps/travelplan_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import bcrypt
from django.db import models
from datetime import date
from django.utils.dateparse import parse_date
import re
EMAIL_REGEX=re.compile(r"(^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)")


class userDBManager(models.Manager):
      def login(self, postData):
          errors=[]
          if( (len(postData['username'])<3) ):
               print "UserName has to be atleast 3characters!"
               errors.append("UserName has to be atleast 3characters!")
          if(len(postData['password'])<8):
               print "Password less than 8characters"
               errors.append("Password needs to be 8 characters long")
          if errors:
              print "Not Created"
              return(False,errors)
          ret_user=userDB.objects.filter(username=postData['username'])
          if ret_user:
              userFound=userDB.objects.get(username=postData['username'])
              password=postData['password'].encode()
                # Check that a unhashed password matches one that has previously been
                #   hashed
              if bcrypt.checkpw(password.encode(), userFound.password.encode()):
                  return(True,userFound)
              else:
                  errors.append("Could not login")
                  return(False,errors)
          else:
              errors.append("Could not login")
              return(False,errors)

      def register(self, postData):
          errors=[]
          print postData
          if(len(postData['name'])<3):
              print "Name is not entered"
              errors.append("Name has to be atleast 3characters!")
          if( (len(postData['username'])<3) ):
              print "Username is not entered correct"
              errors.append("UserName has to be atleast 3characters!")
          if(len(postData['password'])<8):
              print "password less than 8characters"
              errors.append("Password needs to be 8 characters long!")
          if(postData['password']<>postData['confirm_pwd']):
              print "both passwords do not match"
              errors.append("Please confirm password")
          if errors:
              print "not created"
              return(False,errors)
          else:
              ret_user=userDB.objects.filter(username=postData['username'])
              if ret_user:
                  errors.append("Please use different login info!")
                  print "Please use different login info!"
                  return(False,errors)
              print "inside save"
              password=postData['password'].encode();
               # Hash a password for the first time, with a randomly-generated salt
              hashed = bcrypt.hashpw(password, bcrypt.gensalt())
              newUser=userDB(name=postData['name'],username=postData['username'],password=hashed)
              newUser.save()
              return(True,newUser)

class userDB(models.Model):
    name = models.CharField(max_length=45)
    password = models.CharField(max_length=100)
    username=models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects=userDBManager()
class travelplanManager(models.Manager):
    def createTravel(self,postData):
        errors=[]
        date_str=postData['fromdate'].encode()
        dateFrom=parse_date(date_str)
        date_str1=postData['todate'].encode()
        dateTo=parse_date(date_str1)
        dateToday=date.today()
        if(len(postData['destination'])<=0):
            print "Destination needs to be entered"
            errors.append("Destination needs to be entered!")
        if(len(postData['description'])<=0):
            print "Description needs to be entered"
            errors.append("Description needs to be entered!")
        if(  date_str=="" or dateToday > dateFrom ):
            print "From Date entered needs to be later than today"
            errors.append("From Date entered needs to be later than today!")
        if(  date_str1=="" or dateFrom > dateTo):
            print "To Date entered needs to be greater than Start date"
            errors.append("To Date entered needs to be greater than Start date!")
        if errors:
            print "Not Created"
            return(False,errors)
        else:
            currentuser=userDB.objects.get(id=postData['id'])
            traveluser=travelplan(destination=postData['destination'],description=postData['description'],traveldate_from=postData['fromdate'],traveldate_to=postData['todate'],user_travel=currentuser)
            traveluser.save()
            return(True,traveluser)

class travelplan(models.Model):
    destination=models.CharField(max_length=50)
    description=models.TextField()
    traveldate_from=models.DateField()
    traveldate_to=models.DateField()
    user_travel=models.ForeignKey(userDB,related_name='travel_user')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects=travelplanManager()

class tripManager(models.Manager):
    def joinTrip(self,postData,id):
        usertrip=userDB.objects.get(id=postData['userid'])
        traveljoin=travelplan.objects.get(id=id)
        tripplan=trip(user_trip=usertrip,travel_join=traveljoin)
        tripplan.save()
        return(True,tripplan)

class trip(models.Model):
    user_trip=models.ForeignKey(userDB,related_name='trip_user')
    travel_join=models.ForeignKey(travelplan,related_name='join_travel')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects=tripManager()

apps/travelplan_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render,redirect
from .models import userDB,travelplan,trip
from django.db.models import Count, Min, Sum, Avg
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def index(request):
    return render(request,'travelplan_app/index.html')

def register(request):
    if( request.method=='POST'):
        ret_val=userDB.objects.register(request.POST)
        if ret_val[0]:
            newusers=ret_val[1]
            request.session['user']={
                'id':newusers.id,
                'name':newusers.name,
            }
            context={
                "users": newusers
            }
            messages.add_message(request,messages.INFO,"Registered successfully!")
            return redirect('travelplan:travels')
        else:
            for error in ret_val[1]:
                print error;
                messages.error(request,error)
            return redirect('travelplan:index')
    return redirect('travelplan:index')
def login(request):
    if( request.method=='POST'):
        ret_val=userDB.objects.login(request.POST)
        if ret_val[0]:
            newusers=ret_val[1]
            request.session['user']={
                'id':newusers.id,
                'name':newusers.name,
            }
            context={
                "users": newusers
            }
            #messages.add_message(request,messages.INFO,"Logged in successfully!")
            return redirect('travelplan:travels')
        else:
            for error in ret_val[1]:
                print error;
                messages.error(request,error)
            return redirect('travelplan:index')

    return redirect('travelplan:index')


def logout(request):
    request.session.clear()
    return redirect('travelplan:index')

def showadd(request):
    if 'user' in request.session :
        return render(request,'travelplan_app/plan.html')
    return redirect('travelplan:index')

def add(request):
    if 'user' in request.session :
        if( request.method=='POST'):
            ret_val=travelplan.objects.createTravel(request.POST)
        if ret_val[0]:
            newusers=ret_val[1]
        else:
            for error in ret_val[1]:
                print error;
                messages.error(request,error)
            return render(request,'travelplan_app/plan.html')
        return redirect('travelplan:travels')
    return redirect('travelplan:index')

def travels(request):
    if 'user' in request.session :
        if( request.method=='GET'):
            try:
                allusers=trip.objects.all()
                currentuser=userDB.objects.filter(id=request.session['user']['id'])
                newusers=travelplan.objects.filter(user_travel=currentuser)
                usersother=trip.objects.filter(user_trip=currentuser)
                other_users=travelplan.objects.filter(~Q(join_travel__in=trip.objects.filter(user_trip=currentuser)),~Q(user_travel=currentuser)).distinct()
                context={
                    "users": newusers,
                    "joinedtrips" : usersother,
                    "others":other_users,
                    "allusers":allusers
                }
                return render(request,'travelplan_app/travels.html',context)
            except:
                print("Couldnt create Travel plan:DB error")
                messages.error(request,"Couldnt create Travel plan:DB error")
                return redirect('travelplan:travels')
    return redirect('travelplan:index')

def joinTrip(request,id):
    if 'user' in request.session :
        if( request.method=='POST'):
            try:
                retval=trip.objects.joinTrip(request.POST,id)
                return redirect('travelplan:travels')
            except:
                print("Couldnt Join the trip:DB error")
                messages.error(request,"Couldnt Join the trip:DB error")
                return redirect('travelplan:travels')
    return redirect('travelplan:index')

def destination(request,id):
    if 'user' in request.session :
        if( request.method=='GET'):
            try:
                destination=travelplan.objects.get(id=id)
                otherusers=trip.objects.filter(Q(travel_join=destination))
                context={
                    "destination" : destination,
                    "otherusers" : otherusers
                }
                return render(request,'travelplan_app/destination.html',context)
            except:
                print("The destination doesn't exist")
                messages.error(request,"The destination doesn't exist.")
                return render(request,'travelplan_app/destination.html')
    return redirect('travelplan:index')

def delete(request):
    if 'user' in request.session :
            trip.objects.all().delete();
            travelplan.objects.all().delete();
            userDB.objects.all().delete();
            return redirect('travelplan:travels')
    return redirect('travelplan:index')

apps/travelplan_app/templates/travelplan_app/destination.html
<!DOCTYPE HTML>
<html>
<head>
  <meta char='utf-8'>
  <title>Travel Buddy</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'travelplan_app/css/styleplan.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <header>
      <a href={% url 'travelplan:travels' %}>Home</a>
      <a href={% url 'travelplan:logout' %}>Logout</a>
  </header>
  <p>
    {%if messages%}
    {% for message in messages%}
    <h4>{{ message }}</h4>
    {%endfor%}
    {%endif%}
  </p>
  <section>
    <table>
        <tr>{{destination.destination}}</tr>
        <tr><td>Description:</td><td>{{destination.description}}</td></tr>
        <tr><td>Travel Date From:</td><td>{{destination.traveldate_from}}</td></tr>
        <tr><td>Travel Date To:</td><td>{{destination.traveldate_to}}</td></tr>
        <tr><td>Planned By:</td><td>{{destination.user_travel.name}}</td></tr>
    </table>
  </section>
  <p>Other users' joining the trip:</p>
  {%for o in otherusers%}
  <div id="otherusers">
    {{o.user_trip.name}}
  </div>
  {%endfor%}
</body>
</html>

apps/travelplan_app/templates/travelplan_app/index.html
<!DOCTYPE HTML>
<html>
<head>
  <meta char='utf-8'>
  <title>Travel Buddy</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'travelplan_app/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <h3>Welcome!</h3>
  {%if messages%}
  {% for message in messages%}
  <h4>{{ message }}</h4>
  {%endfor%}
  {%endif%}

  <section id="right">
    <h5>Register</h5>
    <form action={% url 'travelplan:register' %} method="post">
      {%csrf_token%}
      <table>
        <tbody>
          <tr>
            <td>Name:</td>
            <td><input type="text" name="name"></td>
          </tr>
          <tr>
            <td>Username:</td>
            <td><input type="text" name="username"></td>
          </tr>
          <tr>
            <td>Password:</td>
            <td><input type="password" name="password"></td>
          </tr>
          <tr>
            <td>Confirm Password:</td>
            <td><input type="password" name="confirm_pwd"></td>
          </tr>
          <tr>
            <td>
            </td>
            <td><button type="submit" value="register">Register</button></td>
          </tr>
        </table>
    </form>
  </section>
  <section id="left">
    <h5>Login</h5>
    <form action={% url 'travelplan:login' %} method="post">
      {%csrf_token%}
      <table>
        <tbody>
          <tr>
            <td>Username:</td>
            <td><input type="text" name="username"></td>
          </tr>
          <tr>
            <td>Password:</td>
            <td><input type="password" name="password"></td>
          </tr>
          <tr>
            <td>
            </td>
            <td><button type="submit" name="login" value="login">Login</button></td>
          </tr>
        </tbody>
      </table>
    </form>
  </section>
</body>
</html>

apps/travelplan_app/templates/travelplan_app/plan.html
<!DOCTYPE HTML>
<html>
<head>
  <meta char='utf-8'>
  <title>Travel Buddy</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'travelplan_app/css/styleplan.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <header>
    <a href="{% url 'travelplan:travels' %}">Home</a>
    <a href={% url 'travelplan:logout' %}>Logout</a>
  </header>
  <section>
    <p>
      {%if messages%}
      {% for message in messages%}
      <h4>{{ message }}</h4>
      {%endfor%}
      {%endif%}
    </p>
    <p>
      Add a Trip
    </p>
    <form action={% url 'travelplan:add' %} method="post">
      {%csrf_token%}
      <input type='hidden' name="id" value="{{request.session.user.id}}">
      <table id="planTable">
        <tbody>
          <tr>
            <td>Destination:</td>
            <td><input type="text" name="destination"></td>
          </tr>
          <tr>
            <td>Description:</td>
            <td><input type="text" name="description"></td>
          </tr>
          <tr>
            <td>Travel Date From</td>
            <td><input type="date" name="fromdate"></td>
          </tr>
          <tr>
            <td>Travel Date To</td>
            <td><input type="date" name="todate"></td>
          </tr>
        </table>
        <button id="addButton" type="submit" value="add">Add</button>
    </form>

  </section>

apps/travelplan_app/templates/travelplan_app/travels.html
<!DOCTYPE HTML>
<html>
<head>
  <meta char='utf-8'>
  <title>Travel Buddy</title>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'travelplan_app/css/style.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <header>
    <div id="travelheader">
      <a href={% url 'travelplan:logout' %}>Logout</a>
    </div>
    <div>
      Hello, {{request.session.user.name}}
    </div>
  </header>
  <section>
    <p>
      {%if messages%}
      {% for message in messages%}
      <h4>{{ message }}</h4>
      {%endfor%}
      {%endif%}
    </p>

    <h3>Your Trip Schedules</h3>
    <hr>
    <table>
      <tr>
        <th>Destination</th>
        <th>Travel Start Date</th>
        <th>Travel End Date</th>
        <th>Plan</th>
      </tr>
      {% for user in users %}
      <tr>
        <td><a href={% url 'travelplan:destination' user.id%}>{{user.destination}}<a></td>
          <td>{{user.traveldate_from}}</td>
          <td>{{user.traveldate_to}}</td>
          <td>{{user.description}}</td>
        </tr>
        {%endfor%}
        {% for joinedtrip in joinedtrips %}
        <tr>
          <td><a href={% url 'travelplan:destination' joinedtrip.travel_join.id %}>{{joinedtrip.travel_join.destination}}</a></td>
          <td>{{joinedtrip.travel_join.traveldate_from}}</td>
          <td>{{joinedtrip.travel_join.traveldate_to}}</td>
          <td>{{joinedtrip.travel_join.description}}</td>
        </tr>
        {% endfor %}
      </table>
    </section>
    <hr>
    <section>
      <h3>Others User's Travel Plans</h3>
      <hr>
      <table>
        <tr>
          <th>Name</th>
          <th>Destination</th>
          <th>Travel Start Date</th>
          <th>Travel End Date</th>
          <th>Do you want to Join?</th>
        </tr>
        {% for otheruser in others %}
        <tr>
          <td>{{otheruser.user_travel.name}}</td>
          <td><a href={% url 'travelplan:destination' otheruser.id %}>{{otheruser.destination}}</a></td>
          <td>{{otheruser.traveldate_from}}</td>
          <td>{{otheruser.traveldate_to}}</td>
          <form action={% url 'travelplan:joinTrip' otheruser.id %} method="post">
            {%csrf_token%}
            <input type='hidden' name="userid" value="{{request.session.user.id}}">
            <td><button type="submit" value="join">Join</button></td>
          </form>
        </tr>
        {% endfor %}
      </table>
    </section>
    <section>
      <div id="addtravel">
        <p>
          <a href={% url 'travelplan:showadd' %}>Add a Travel Plan</a>
        </p>
      </div>
    </section>
  </body>
  </html>